import type { Metadata } from "next";
import "@fontsource/ibm-plex-sans/400.css";
import "@fontsource/ibm-plex-sans/500.css";
import "@fontsource/ibm-plex-mono/400.css";
import "@fontsource/ibm-plex-mono/500.css";
import "./globals.css";
import Nav from "@/components/Nav";
import { lastRun } from "@/lib/data";

export const metadata: Metadata = {
  title: "ORION · Cross-asset macro intelligence",
  description: "Explainable FX and commodity signals, regimes, walk-forward backtests and a rules-based paper portfolio.",
  robots: { index: true, follow: true },
};

export const revalidate = 600;

async function Freshness() {
  const run = await lastRun();
  if (!run) return <span className="fresh"><i className="dot" /> <span className="label">awaiting first run</span></span>;
  const ended = run.finished_at ?? run.started_at;
  const hrs = (Date.now() - new Date(ended).getTime()) / 3_600_000;
  const cls = run.status !== "success" ? "bad" : hrs > 80 ? "stale" : "ok";
  const when = new Date(ended).toLocaleString("en-GB", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit", timeZone: "Asia/Singapore" });
  return (
    <span className="fresh" title={`Last pipeline run: ${run.status}`}>
      <i className={`dot ${cls}`} /> <span className="label">updated</span> {when} SGT
    </span>
  );
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div className="shell">
          <header className="topbar">
            <a href="/" className="brand">ORION<small>cross-asset macro intelligence</small></a>
            <Nav />
            <Freshness />
          </header>
          {process.env.NEXT_PUBLIC_DEMO_MODE === "1" && (
            <div className="notice" style={{ marginTop: 12 }}>
              <b>Demo mode.</b> Every number on this site is synthetic, generated by running the real pipeline on simulated markets. Nothing here reflects actual prices.
            </div>
          )}
          <main>{children}</main>
          <footer className="foot">
            <span>Research and paper trading only. Nothing here is investment advice.</span>
            <span>Data: FRED, U.S. Treasury/Fed H.15 &amp; H.10, BLS, Chicago Fed, CBOE (VIX), MoF Japan, ECB, RBA, Bank of Canada, U.S. EIA, OANDA. See <a href="/methodology#sources">sources</a>.</span>
          </footer>
        </div>
      </body>
    </html>
  );
}
